packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  sharp: true

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAgeExclude:
  - vite@8.1.4
  - '@humanspeak/svelte-motion@0.7.16'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
