packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  sharp: true

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAgeExclude:
  - vite@8.1.4
  - '@humanspeak/svelte-motion@0.7.16 || 0.7.18'
  - postcss@8.5.17

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
