packages:
    - apps/*
    - packages/*

allowBuilds:
    esbuild: true
    sharp: true

ignoredBuiltDependencies:
    - esbuild

minimumReleaseAgeExclude:
    - vite@8.1.4

onlyBuiltDependencies:
    - '@tailwindcss/oxide'
    - esbuild
