#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

currentBranch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$currentBranch" = "main" ]; then
  echo "You can't commit directly to main branch"
  exit 1
fi

docker run -u node --rm -v $PWD/.npmrc:/home/node/app/.npmrc -v $PWD/:/home/node/app -w /home/node/app node:16.16 sh -c '[ ! -d ./node_modules ] && npm install ; npm run lint'