#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

docker run -u node --rm -v $PWD/.npmrc:/usr/src/app/.npmrc -v $PWD/:/usr/src/app -w /usr/src/app node:16.14 sh -c '[ ! -d ./node_modules ] && npm install ; npm run lint'